language: node_js
node_js:
    - "node"
    - "12"
sudo: required
services:
  - xvfb
dist: focal
cache:
  directories:
    - node_modules
env:
  global:
    - CXX=g++-4.8
    - DISPLAY=:99.0
    - CHROME_BIN=/usr/bin/google-chrome
# installing Chrome for e2e tests
addons:
  chrome: beta
# the following step should start the virtual X frame buffer: Xvfb process
before_script:
  - sleep 3 #wait a while before xvfb to start

script:
  - npm test

after_script:
  - "sh -e /etc/init.d/xvfb stop"