language: node_js
node_js:
    - "node"
    - "12"

addons:
  chrome: stable

cache:
  directories:
     - ./node_modules

install:
  - npm install

script:
  - npm run test-travis -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  - npm start & wait-on http://localhost:3000