language: node_js
node_js:
    - "node"
    - "12"
sudo: required
dist: trusty
cache:
  directories:
    - node_modules
language: node_js
# setting up environment variables
env:
  global:
    - CXX=g++-4.8
    - DISPLAY=:99.0
    - CHROME_BIN=/usr/bin/google-chrome
# installing Chrome for e2e tests
addons:
  apt:
    sources:
      - google-chrome
# the following step should start the virtual X frame buffer: Xvfb process
before_script:
  - CHROME_BIN=chromium-browser
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 #wait a while before xvfb to start

script:
  - npm test

after_script:
  - "sh -e /etc/init.d/xvfb stop"