language: node_js
node_js:
    - "node"
    - "12"

sudo: false

git:
    submodules: false

addons:
  apt:
    packages:
      - google-chrome-stable

before_script:
    - npm install

script:
    - npm test

after_success:
    - npm run report-coveralls
    - npm run report-codecov